openapi: 3.0.3
info:
  title: Space Service API
  description: |
    공간 관리 서비스 API 명세서입니다.<br>
    사이트, 시설물, 구획, 구역, 출입 지점(Access Point) 등 물리적 공간과 관련된 리소스를 관리합니다.
  version: 1.0.0
  contact:
    name: "Jehyun Kim"

servers:
  - url: http://localhost:4300/api/v1/space
    description: "로컬 개발 서버"     

tags:
  - name: 5. Access Point Management
    description: 출입 지점(문/게이트) 관리

paths:
  /access-points:
    get:
      tags: ["5. Access Point Management"]
      summary: "출입 포인트(Access Point) 목록 조회"
      description: |
        물리적 출입 포인트 목록을 조회합니다.<br>
        상위 공간(`site`, `facility`, `sector`) 및 구역(`area`)별 조회나 타입(`type`)별 필터링을 지원합니다.
      parameters:
        - name: "organizationId"
          in: "query"
          schema:
            type: "string"
            format: "uuid"
        - name: "siteId"
          in: "query"
          description: "소속 사이트 ID 필터"
          schema:
            type: "string"
            format: "uuid"
        - name: "facilityId"
          in: "query"
          description: "소속 시설물(건물) ID 필터"
          schema:
            type: "string"
            format: "uuid"
        - name: "sectorId"
          in: "query"
          description: "소속 구획(층) ID 필터"
          schema:
            type: "string"
            format: "uuid"
        - name: "areaId"
          in: "query"
          description: "소속 구역 ID 필터"
          schema:
            type: "string"
            format: "uuid"
        - name: "name"
          in: "query"
          description: "출입 포인트명 검색 (부분 일치)"
          schema:
            type: "string"
        - name: "type"
          in: "query"
          description: "출입 포인트 타입 필터"
          schema:
            type: "string"
            enum: ["DOOR", "GATE_DOOR", "TURNSTILE", "ELEVATOR", "SPEED_GATE", "BARRIER", "SLIDING", "SHUTTER", "BOLLARD"]
        - name: "isActive"
          in: "query"
          schema:
            type: "boolean"
        - name: "page"
          in: "query"
          schema:
            type: "integer"
            default: 0
        - name: "size"
          in: "query"
          schema:
            type: "integer"
            default: 1000
        - name: "sort"
          in: "query"
          description: |
            정렬 기준 (형식: 필드명,정렬방향)<br>
            예: name,asc (이름순), createdAt,desc (최신순)<br>
            다중 정렬 가능
          schema:
            type: "array"
            items:
              type: "string"
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  content:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/AccessPoint"
                  page:
                    $ref: "#/components/schemas/PageMetadata"
    post:
      tags: ["5. Access Point Management"]
      summary: "출입 포인트 생성"
      description: |
        새로운 물리적 출입 포인트을 생성합니다.
        
        **주요 특징:**
        - **공간 정보:** `siteId`, `facilityId`, `sectorId`, `areaId` 중 하나 이상을 입력하여 위치를 지정할 수 있습니다. (모두 선택 사항)
        - **보안 설정:** 입실/퇴실에 대한 인증 규칙(`AuthenticationRule`)과 최소 보안 임계값(`SecurityThreshold`)을 직접 설정합니다.
        - **장비 연결:** `devices` 배열을 통해 입/출 리더기나 컨트롤러 등 물리적 장비를 즉시 연결할 수 있습니다.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccessPointRequest"
      responses:
        '200':
          description: "생성됨"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessPoint"
        '409':
          $ref: "#/components/responses/Conflict"

  /access-points/types:
    get:
      tags: ["5. Access Point Management"]
      summary: "출입 포인트 타입 목록 조회"
      description: |
        시스템에서 지원하는 출입 포인트 타입(Enum) 목록을 조회합니다.<br>
        출입 포인트 타입(Enum) 목록:<br>
        `"DOOR", "GATE_DOOR", "TURNSTILE", "ELEVATOR", "SPEED_GATE", "BARRIER", "SLIDING", "SHUTTER", "BOLLARD"`<br>
        UI 드롭다운(Select Box) 구성에 사용됩니다.<br>
        반환 예시: <br>
        `[{ "code": "DOOR", "label": "일반 출입문" }, { "code": "TURNSTILE", "label": "스피드 게이트" }]`
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/AccessPointType"  

  /access-points/{id}:
    get:
      tags: ["5. Access Point Management"]
      summary: "출입 포인트 단건 조회"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        '200':
          description: "성공"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessPoint"
        '404':
          $ref: "#/components/responses/NotFound"

    put:
      tags: ["5. Access Point Management"]
      summary: "출입 포인트 수정"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccessPointRequest"
      responses:
        '200':
          description: "수정됨"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessPoint"
        '404':
          $ref: "#/components/responses/NotFound"
        '409':
          $ref: "#/components/responses/Conflict"

    delete:
      tags: ["5. Access Point Management"]
      summary: "출입 포인트 삭제"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        '200':
          description: "삭제 성공"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteResult"
        '404':
          $ref: "#/components/responses/NotFound"

components:
  responses:
    BadRequest:
      description: "잘못된 요청 (유효성 검사 실패 등)"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Unauthorized:
      description: "인증 실패 (토큰 없음/만료)"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Forbidden:
      description: "권한 없음"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: "리소스를 찾을 수 없음"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Conflict:
      description: "데이터 충돌 (중복 등)"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    InternalServerError:
      description: "서버 내부 오류"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    # ----------------------------------------------------
    # Common Schemas
    # ----------------------------------------------------
    PageMetadata:
      type: "object"
      properties:
        size:
          type: "integer"
          description: "페이지 당 항목 수"
          example: 20
        page:
          type: "integer"
          description: "현재 페이지 번호 (0부터 시작)"
          example: 0
        totalElements:
          type: "integer"
          description: "전체 항목 수"
          example: 100
        totalPages:
          type: "integer"
          description: "전체 페이지 수"
          example: 5
        isLast:
          type: "boolean"
          description: "마지막 페이지 여부"
          example: false
        hasNext:
          type: "boolean"
          description: "다음 페이지 존재 여부"
          example: true

    DeleteResult:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          description: "삭제된 리소스의 ID"
        isSoftDeleted:
          type: "boolean"
          description: "논리적 삭제(Soft Delete) 여부. true면 DB에는 남아있지만 삭제된 것으로 처리됨."
        isHardDeleted:
          type: "boolean"
          description: "물리적 삭제(Hard Delete) 여부. true면 DB에서 완전히 제거됨."

    ErrorResponse:
      type: "object"
      properties:
        errorCode:
          type: "string"
          description: "에러 코드 (예: DUPLICATE_ENTRY, RESOURCE_NOT_FOUND)"
          example: "INVALID_REQUEST"
        errorMessage:
          type: "string"
          description: "에러 메시지"
          example: "잘못된 요청입니다."
        errorDetails:
          type: "object"
          description: "상세 에러 내용 (필드별 유효성 검사 실패 사유 등)"
          nullable: true

    AccessPointDevice:
      type: "object"
      description: "출입 지점에 연결된 장비 상세 정보"
      properties:
        deviceId:
          type: "string"
          format: "uuid"
        deviceName:
          type: "string"
          description: "장비명"
          example: "정문 입실 리더기"
        deviceCode:
          type: "string"
          description: "장비 코드"
          example: "DEV-READER-001"
        deviceType:
          type: "string"
          enum: ["ACU", "READER", "CONTROLLER", "CAMERA", "SENSOR"]
          description: "장비 타입 (ACU, READER, CONTROLLER, CAMERA, SENSOR)"
        deviceRole:
          type: "string"
          enum: ["ENTRY", "EXIT", "CONTROLLER", "SENSOR"]
          description: "이 출입 지점에서의 역할"
        portIndex:
          type: "integer"
          description: "연결 포트 번호" 
        authenticationModes:
          type: "array"
          items:
            type: "string"
            enum: ["CARD", "PIN", "BIOMETRIC", "MOBILE"]
          description: "인증 타입 (리더기인 경우)"

    AccessPointRequest:
      type: "object"
      required: ["name", "type", "securityConfig"]
      description: |
        출입 지점 생성/수정 요청 객체.<br>
        `siteId`, `facilityId`, `sectorId`, `areaId` 중 하나를 선택하여 공간을 지정합니다.<br>
        **보안 설정(Security Config):** <br>
        - **보안 임계값(Threshold):** ID 참조와 직접 값 입력을 모두 지원하는 하이브리드 방식입니다. ID가 입력되면 ID의 정책을 따르고, ID가 없으면 직접 입력된 값(Level)을 사용합니다.<br>
        - **인증 규칙(Authentication):** 오직 ID 참조만 가능합니다. (직접 입력 불가)
      properties:
        siteId:
          type: "string"
          format: "uuid"
          nullable: true
          description: "소속 사이트 ID (선택)"
        facilityId:
          type: "string"
          format: "uuid"
          nullable: true
          description: "소속 시설물 ID (선택)"
        sectorId:
          type: "string"
          format: "uuid"
          nullable: true
          description: "소속 층/구획 ID (선택)"
        areaId:
          type: "string"
          format: "uuid"
          nullable: true
          description: "소속 구역 ID (선택)"
        name:
          type: "string"
        description:
          type: "string"
        code:
          type: "string"
        type:
          type: "string"
          enum: ["DOOR", "GATE_DOOR", "TURNSTILE", "ELEVATOR", "SPEED_GATE", "BARRIER", "SLIDING", "SHUTTER", "BOLLARD"]
          default: "DOOR"
        fromAreaId:
          type: "string"
          format: "uuid"
          nullable: true
        toAreaId:
          type: "string"
          format: "uuid"
          nullable: true
        config:
          type: "object"
          nullable: true
          description: "하드웨어 제어 설정 (개방 시간 등)"
        securityConfig:
          type: "object"
          required: ["entryAuthenticationRuleId", "exitAuthenticationRuleId"]
          properties:
            # --- [보안 설정 - 입실 (Entry)] ---
            entrySecurityThresholdId:
              type: "string"
              format: "uuid"
              nullable: true
              description: "[하이브리드] 입실 보안 임계값 ID (우선 적용)"
            entryAccessLevel:
              type: "integer"
              nullable: true
              default: 0
              minimum: 0
              description: "[하이브리드] 입실 출입 레벨 직접 지정 (ID 미지정 시 적용, 미입력 시 0)"
            entryAntipassbackLevel:
              type: "integer"
              nullable: true
              default: 0
              minimum: 0
              description: "[하이브리드] 입실 안티패스백 레벨 직접 지정 (ID 미지정 시 적용, 미입력 시 0)"
            entryArmingLevel:
              type: "integer"
              nullable: true
              default: 0
              minimum: 0
              description: "[하이브리드] 입실 경비(Arming) 레벨 직접 지정 (ID 미지정 시 적용, 미입력 시 0)"

            # --- [보안 설정 - 퇴실 (Exit)] ---
            exitSecurityThresholdId:
              type: "string"
              format: "uuid"
              nullable: true
              description: "[하이브리드] 퇴실 보안 임계값 ID (우선 적용)"
            exitAccessLevel:
              type: "integer"
              nullable: true
              default: 0
              minimum: 0
              description: "[하이브리드] 퇴실 출입 레벨 직접 지정 (ID 미지정 시 적용, 미입력 시 0)"
            exitAntipassbackLevel:
              type: "integer"
              nullable: true
              default: 0
              minimum: 0
              description: "[하이브리드] 퇴실 안티패스백 레벨 직접 지정 (ID 미지정 시 적용, 미입력 시 0)"
            exitArmingLevel:
              type: "integer"
              nullable: true
              default: 0
              minimum: 0
              description: "[하이브리드] 퇴실 경비(Arming) 레벨 직접 지정 (ID 미지정 시 적용, 미입력 시 0)"
        devices:
          type: "array"
          description: "출입 포인트 생성 시 연결할 장비 목록"
          items:
            $ref: "#/components/schemas/AccessPointDeviceRequest"

    AccessPointConfig:
      type: "object"
      description: "출입 지점의 보안 정책 설정 정보 (하이브리드 지원)"
      properties:
        
        # --- [입실] ---
        entrySecurityThresholdId:
          type: "string"
          format: "uuid"
          description: "입실 보안 임계값 ID"
          nullable: true
        entryAccessLevel:
          type: "integer"
          description: "입실 출입 레벨"
          nullable: true
        entryAntipassbackLevel:
          type: "integer"
          description: "입실 안티패스백 레벨"
          nullable: true
        entryArmingLevel:
          type: "integer"
          description: "입실 경비 레벨"
          nullable: true
        
        # --- [퇴실] ---
        exitSecurityThresholdId:
          type: "string"
          format: "uuid"
          description: "퇴실 보안 임계값 ID"
          nullable: true
        exitAccessLevel:
          type: "integer"
          description: "퇴실 출입 레벨"
          nullable: true
        exitAntipassbackLevel:
          type: "integer"
          description: "퇴실 안티패스백 레벨"
          nullable: true
        exitArmingLevel:
          type: "integer"
          description: "퇴실 경비 레벨"
          nullable: true

    AccessPointType:
      type: "object"
      properties:
        code:
          type: "string"
          description: "출입 포인트 타입 코드 (DB 저장 값)"
          example: "DOOR"
        label:
          type: "string"
          description: "화면 표시용 라벨"
          example: "일반 출입문"

    AccessPoint:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        siteId:
          type: "string"
          format: "uuid"
          description: "소속 사이트 ID"
        facilityId:
          type: "string"
          format: "uuid"
          description: "소속 시설물 ID"
        sectorId:
          type: "string"
          format: "uuid"
          description: "소속 구획 ID"
        areaId:
          type: "string"
          format: "uuid"
          description: "소속 구역 ID"
        siteName:
          type: "string"
          description: "[Read-Only] 소속 사이트명"
          example: "본사 캠퍼스"
          readOnly: true
        facilityName:
          type: "string"
          description: "[Read-Only] 소속 시설물명"
          example: "본관 빌딩"
          readOnly: true
        sectorName:
          type: "string"
          description: "[Read-Only] 소속 구획명"
          example: "3층"
          readOnly: true
        areaName:
          type: "string"
          description: "[Read-Only] 소속 구역명"
          example: "보안구역 A"
          readOnly: true
        name:
          type: "string"
          example: "본관 1층 정문"
        description:
          type: "string"
          example: "본관 빌딩 1층에 위치한 주요 출입문"
        code:
          type: "string"
          example: "AP-ENT-001"
        type:
          type: "string"
          enum: ["DOOR", "GATE_DOOR", "TURNSTILE", "ELEVATOR", "SPEED_GATE", "BARRIER", "SLIDING", "SHUTTER", "BOLLARD"]
        fromAreaId:
          type: "string"
          format: "uuid"
          description: "진입 전 구역 ID (안티패스백용)"
        toAreaId:
          type: "string"
          format: "uuid"
          description: "진입 후 구역 ID (안티패스백용)"
        config:
          type: "object"
          description: "하드웨어 제어 관련 설정 (개방 시간, 릴레이 등)"
        securityConfig:
          $ref: "#/components/schemas/AccessPointConfig"
          description: "적용된 보안 정책 정보 (등급, 인증 규칙 등)"
        devices:
          type: "array"
          items:
            $ref: "#/components/schemas/AccessPointDevice"
          description: "연결된 물리적 장비 목록"
        isActive:
          type: "boolean"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"

    AccessPointDeviceRequest:
      type: "object"
      required: ["deviceId", "deviceRole"]
      properties:
        deviceId:
          type: "string"
          format: "uuid"
          description: "연결할 장비 ID"
        deviceRole:
          type: "string"
          enum: ["ENTRY", "EXIT", "CONTROLLER", "SENSOR"]
          description: |
            장비의 역할 (입실 리더기, 퇴실 리더기, 컨트롤러 등)<br>
            ENTRY는 from->to 정방향, EXIT는 to->from 역방향 이동을 유발합니다.
        portIndex:
          type: "integer"
          description: "컨트롤러 연결 포트 번호 (선택 사항)"
        authenticationModes:
          type: "array"
          items:
            type: "string"
            enum: ["CARD", "PIN", "BIOMETRIC", "MOBILE"]
          description: "인증 타입 (리더기인 경우, 선택 사항)"
